### ISSUE TITLE
Cell types DWLS

### ISSUE THREAD

**Issue by kathireinisch** [PelzKo/immunedeconv2#40]
In case you didn't notice, DWLS replaces spaces by _ in the cell type annotations. This is kind of annoying when you want to plot your data... 
My first thought was we could simply replace _ by spaces at the end of the deconvolution, but what if someone had _ in their cell type annotations on purpose and we 'destroy' this by adding spaces. We could also check their cell type annotations after deconvolution, but then they would also have to provide this parameter for dwls. 
What are your thoughts on this? Do you guys think it's important to change it or should we just mention it somewhere?

On a second thought, column names containing spaces aren't that nice for plotting either... Tbh I don't know what's best

**Comment by kathireinisch** [comment]
I just realized, Scaden replaces spaces by dots. (Bisque and MOMF leave spaces as they are, DWLS changes it to _, Scaden to .) So every method has a different output. Maybe we should just write that in the documentation?

**Comment by grst** [comment]
would be great if the outputs were consistent... you could just call `make.names` on the cell types before feeding them into any of the methods (or even just assign each cell type a numeric id). At the end of the deconvolute function you could then map it back to the original cell types.

**Comment by nicolasgoedert97** [comment]
@kathireinisch I changed Scaden to replace the . with spaces. :)

**Comment by kathireinisch** [comment]
oh i actually already found a solution for this, if someone wanted to look over my latest pull request :)
anyhow, thanks @nicolasgoedert97, i'll have a look at your solution if it makes more sense than mine!
