### ISSUE TITLE
Finalise package input formats and output formats

### ISSUE THREAD

**Issue by PelzKo** [PelzKo/immunedeconv2#7]
Maybe a SingleCellExperiment is more appropriate than an ExpressionSet
We can also expect that many people already have their single-cell data in this format, or in seurat format.

What kinds of input data do we allow, how do we convert everything

**Comment by grst** [comment]
@nicolasgoedert97 is this completed?

**Comment by nicolasgoedert97** [comment]
@grst almost, build_model() can now be called with either a SingleCellExperiment, AnnData or matrix + annotation. But i just noticed i forgot to do the same for the deconvolute() function, here it still only accepts matrix + annotation. I will add it here too.

**Comment by nicolasgoedert97** [comment]
I added it and created a pull request. If the pull request is ok, i think this issue can be closed.
